### ISSUE TITLE
[CC-1] The Compute Image should be pre-installed with necessary softwares and tools to bootstrap a new Cloud

### ISSUE THREAD

**Issue by peterbean410** [BeanCloudServices/cloud-controller#1]
1. MicroK8s
2. ClusterAPI
3. Placeholder K8s Controller created using Operator framework
4. Firezone deployed to MicroK8s
5. Keycloak deployed to MicroK8s

**Comment by henrypham67** [comment]
Could you please explain what Placeholder K8s Controller is? Is it related to Controller Runtime?

**Comment by peterbean410** [comment]
@HieuMinh67 placeholder K8s Controller means it will create a "hello-world" operator called cloud-project-service-operator using the Operator Framework.
