### ISSUE TITLE
[CC-7] Workflow Manual Trigger to copy a branch from a forked repo to a branch in own repo

### ISSUE THREAD

**Issue by peterbean410** [BeanCloudServices/cloud-controller#7]
Given a PR from a forked repo at branch User/feat-branch to own repo Owner/master
When the workflow is triggered manually
Then User/feat-branch should be copied to Owner/forks/user/feat-branch

**Comment by henrypham67** [comment]
Which repository that the workflow is triggered from ? The Owner repo or the User repo?

**Comment by peterbean410** [comment]
> Which repository that the workflow is triggered from ? The Owner repo or the User repo?

What is the benefit for the workflow to be triggered from the User repo ?
